name: CICD

# Start CICD only on pull request against the main branch
on:
  push:
    branches: [ main ]

  # This workflow dispatch, allows us to execute this workflow manually
  workflow_dispatch:

# Postgresql data is coming from application.properties file, because of CI/CD execution, which means we are not deploy this data to the server
env:
  # Postgres
  POSTGRESQL_VERSION: 13.7
  POSTGRESQL_DB: syscomz
  POSTGRESQL_USER: syscomz
  POSTGRESQL_PASSWORD: password
  # Java
  JAVA_VERSION: 11
  # DockerHub
  DOCKER_HUB_USERNAME: bdostumski
  # AWS & Elastic Bean Stalk
  AWS_REGION: eu-west-2
  # Get Environment and Application names from AWS
  EB_ENVIRONMENT_NAME: Springbootreactfullstack-env
  EB_APPLICATION_NAME: springboot-react-fullstack
  # This is my local docker-compose.yml
  EB_DEPLOYMENT_PACKAGE: elasticbeanstalk/docker-compose.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.7
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: 8398a7/action-slack@v3 # Allow us to send Slack notifications
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # this is the tabs that will be showed into slack message
          text: 'CICD ongoing... :eyes:' # This is the title of the message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # comes from GitHub secrets

      - uses: actions/checkout@v2 # Checkout the code

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')" # this is the build number of our image as date

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a # Docker login action
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # comes from GitHub secrets created from me

      - name: Maven Clean Package and Push to Dockerhub
        # this is maven profiles to bundle FE and BE applications and to build and deploy docker image
        # line 75 come from code in line 59
        run: |
          ./mvnw --no-transfer-progress clean package \
            -P bundle-backend-and-frontend \
            -P jib-build-docker-image-and-push-it-to-docker-hub \
              -Dapp.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}}
      - uses: 8398a7/action-slack@v3 # trigger Slack message
        with:
          status: ${{ job.status }} # with status about the task
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # tags into our message
          text: ':white_check_mark: pushed bdostumski/springboot-react-fullstack:${{steps.build-number.outputs.BUILD_NUMBER}} to docker hub... https://hub.docker.com/repository/docker/bdostumski/springboot-react-fullstack'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # comes from GitHub secrets
      - name: Update and commit app version in docker-compose.yaml
        run: |
          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          sed -i -E 's_(bdostumski/springboot-react-fullstack:)([^"]*)_\1'${BUILD_NUMBER}'_' elasticbeanstalk/docker-compose.yml
          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add elasticbeanstalk/docker-compose.yml
          git commit -m "new app version: ${BUILD_NUMBER}"
          git push

      - uses: 8398a7/action-slack@v3 # Another Slack message
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':elasticbeanstalk: :aws: Deployment started... :grimacing: :crossed_fingers:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # comes from GitHub secrets
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408 # beanstalk deploy
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} # comes from GitHub secrets
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # comes from GitHub secrets
          region: ${{ env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: Version ${{steps.build-number.outputs.BUILD_NUMBER}} deployed via github actions ${{ github.sha }}
          wait_for_deployment: 60
      - uses: 8398a7/action-slack@v3 # End of the job Slack message
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':tada: :arrow_right: Springbootreactfullstack-env.eba-hvmssp8z.eu-west-2.elasticbeanstalk.com'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # comes from GitHub secrets
        if: always() # if the build fails the line from line 115 to the end will always triggered